# this is python image that will be used 
FROM python:3.12-slim


# Set environment variables for the image
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory inside the container to /app
WORKDIR /app

